export const ALERT_THRESHOLDS = {
  TEMPERATURE: {
    WARNING_HIGH: 35,
    CRITICAL_HIGH: 40,
    WARNING_LOW: 10,
    CRITICAL_LOW: 5,
  },
  SOIL_MOISTURE: {
    WARNING_LOW: 30,
    CRITICAL_LOW: 20,
  },
  AIR_HUMIDITY: {
    WARNING_HIGH: 85,
  },
  LIGHT_INTENSITY: {
    WARNING_LOW: 3000,
  },
  PEST_RISK: {
    TEMP_THRESHOLD: 28,
    HUMIDITY_THRESHOLD: 80,
  }
};
