# version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://backend:5000
